# Mostly copy-paste from https://github.com/kiddivouchers/php-timecop/blob/master/.github/workflows/build.yml
name: Build fakerandom
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: PHP ${{ matrix.php-version }} (ZTS ${{ matrix.php-zts }})
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        php-version:
#          - '5.6'
#          - '7.0'
#          - '7.1'
#          - '7.2'
#          - '7.3'
#          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
        php-zts:
          - nts
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
        env:
          phpts: ${{ matrix.php-zts }}
      - name: Set PHP_API
        run: |
          echo "PHP_API=$(php-config --phpapi)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          phpize
          php build/gen_stub.php
          ./configure
          make
          make test REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TESTS="--show-all"
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: fakerandom_${{ env.PHP_API }}.so
          path: modules/fakerandom.so
          if-no-files-found: error
  package:
    name: Package for download
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Combine artifacts
        run: |
          mkdir -p output
          for dir in fakerandom_*.so; do
            # Move/rename from fakerandom.so to fakerandom_PHPAPI.so
            mv "${dir}/fakerandom.so" "output/${dir}"
          done
          cd output
          sha256sum *.so > SHA256SUM
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
      - name: Upload release assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: output
